language: python

dist: xenial

services:
  - postgresql

python:
  - 3.6-dev   # 3.6 development branch
  - 3.6       # 3.6 stable/release
  - 3.7-dev   # 3.7 development branch
  - 3.7       # 3.7 Stable/release
  - 3.8-dev   # 3.8 development branch
  - 3.8

stages:
  - compile
  - test
  - run
  # - deploy
    # if: branch = master

install:
  # Install required libraries.
  - pip install -r requirements.txt

before_script:
  # Create a postgres database.
  - psql -c 'create database koneko;' -U postgres
  - PROJECT_ROOT=$(pwd)
  - cd src/utils/database
  - cp config.example.json config.json
  - cd $PROJECT_ROOT

jobs:
  allow_failures:
    - python: 3.8
  include:
    # Compile all files.
    - stage: compile
      script:
        - python -m compileall ./KonekoBot.py
        - python -m compileall ./src/core
        - python -m compileall ./src/cogs
        - python -m compileall ./src/utils
        - python -m compileall ./tests
    # Run tests
    - stage: test
      python: '3.7'
      name: "pep8 conformance"
      script: python ./tests/pep8.py
    # Force a boot.
    - stage: run
      python: '3.7'
      script: python KonekoBot.py -d 1
    # - stage: deploy
      # deploy to ssh
      # reboot bot

cache: pip
