language: python

dist: xenial

services:
  - postgresql

stages:
  - compile
  - test
  - run
  # - deploy
    # if: branch = master

install:
  # Install required libraries.
  - pip install -r requirements.txt

before_script:
  # Create a postgres database.
  - psql -c 'create database koneko;' -U postgres
  - PROJECT_ROOT=$(pwd)
  - cd src/utils/database
  - cp config.example.json config.json
  - cd $PROJECT_ROOT

jobs:
  include:
    # Compile all files.
    - stage: compile
      script: ./.travis/lint.sh
      python: 3.6-dev       # 3.6 development branch
    - stage: compile
      script: ./.travis/lint.sh
      python: 3.6       # 3.6 stable/release
    - stage: compile
      script: ./.travis/lint.sh
      python: 3.7-dev   # 3.7 development branch
    - stage: compile
      script: ./.travis/lint.sh
      python: 3.7       # 3.7 Stable/release
    - stage: compile
      script: ./.travis/lint.sh
      python: 3.8-dev   # 3.8 development branch

    # Run tests
    - stage: test
      python: 3.7
      name: "pep8 conformance"
      script: ./.travis/tests.sh

    # Force a boot.
    - stage: run
      python: 3.7
      script: python KonekoBot.py -d 1

    # - stage: deploy
      # deploy to ssh
      # reboot bot

  allow_failures:
    - stage: compile
      script: ./.travis/lint.sh
      python: 3.8       # 3.8 Stable/release (not yet out)

cache: pip
