language: python

dist: xenial

services:
  - postgresql

stages:
  - compile
  - quality
  - test
  - run

script:
  - find . | grep -E "\.py$" | xargs python -m compileall

jobs:
  include:
    # Compile all files.
    - stage: compile
      python: 3.7       # 3.7 Stable/release
    - python: 3.8-dev   # 3.8 development branch
    - python: 3.8       # 3.8 Stable/release

    # Run tests
    - stage: quality
      python: 3.8
      name: "Code quality insurance"
      install:
        - pip install pycodestyle
        - pip install flake8
        - pip install pylint
      script:
        - pycodestyle . --ignore=E501
        - flake8
        - pylint -j 0 src

    - stage: test
      python: 3.8
      name: "Unit tests"
      install:
        - pip install -r tests/requirements.txt
        - pip install coveralls
      script:
        - coverage run --source=src -m unittest discover
      after_success:
        - coveralls

    # Force a boot.
    - stage: run
      python: 3.8
      install:
        # Install required libraries.
        - pip install -r requirements.txt
      before_script:
        # Copy configuration files.
        - cp config.example.ini config.ini
      script:
        - python KonekoBot.py 1

cache: pip
