language: python

dist: xenial

services:
  - postgresql

stages:
  - compile
  - test
  - run
  # - deploy
    # if: branch = master

script:
  - find . | grep -E "\.py$" | xargs python -m compileall

jobs:
  include:
    # Compile all files.
    - stage: compile
      python: 3.7-dev   # 3.7 development branch
    - stage: compile
      python: 3.7       # 3.7 Stable/release
    - stage: compile
      python: 3.8-dev   # 3.8 development branch
    - stage: compile
      python: 3.8       # 3.8 Stable/release

    # Run tests
    - stage: test
      python: 3.7
      name: "Code quality insurance"
      install:
        - pip install pycodestyle
        - pip install flake8
        - pip install pylint
      script:
        - pycodestyle . --ignore=E501
        - flake8
        - pylint -j 0 src

    # Force a boot.
    - stage: run
      python: 3.7
      install:
        # Install required libraries.
        - pip install -r requirements.txt
      before_script:
        # Create a postgres database.
        - psql -c 'create database koneko;' -U postgres
        - CONFIG_DIR='src/utils/database'
        - cp $CONFIG_DIR/config.example.json $CONFIG_DIR/config.json
        # Copy configuration files.
        - cp config.example.ini config.ini
      script:
        - python KonekoBot.py -d 1

    # - stage: deploy
      # deploy to ssh
      # reboot bot

cache: pip
