language: python

dist: xenial

services:
  - postgresql

python:
  - 3.6-dev   # 3.6 development branch
  - 3.6       # 3.6 stable/release
  - 3.7-dev   # 3.7 development branch
  - 3.7       # 3.7 Stable/release
  - 3.8-dev   # 3.8 development branch
  - 3.8

install:
  # Install required libraries.
  - pip install -r requirements.txt

before_script:
  # Create a postgres database.
  - psql -c 'create database koneko;' -U postgres
  - PROJECT_ROOT=$(pwd)
  - cd src/helpers/database
  - cp config.example.json config.json
  - cd $PROJECT_ROOT

script:
  # Lint all files.
  - python -m compileall ./KonekoBot.py
  - python -m compileall ./src/core
  - python -m compileall ./src/cogs
  - python -m compileall ./src/helpers

  # Force a boot.
  - python KonekoBot.py -d 1

matrix:
  allow_failures:
    - python: 3.8

cache: pip
