language: python

dist: xenial

addons:
  apt:
    sources:
    packages:

python:
  - 3.6-dev   # 3.6 development branch
  - 3.6       # 3.6 stable/release
  - 3.7-dev   # 3.7 development branch
  - 3.7       # 3.7 Stable/release
  - 3.8-dev   # 3.8 development branch
  - 3.8

install:
  - pip install -r requirements.txt

before_script:
  - PROJECT_ROOT=$(pwd)
  - cd src/helpers/database
  - printf '' > config.json
  - cd $PROJECT_ROOT

script:
  - python -m compileall ./KonekoBot.py
  - python -m compileall ./src/core
  - python -m compileall ./src/cogs
  - python -m compileall ./src/helpers

  - python KonekoBot.py -d 1

matrix:
  allow_failures:
    - python: 3.8

cache: pip
