language: python

dist: xenial

addons:
  apt:
    sources:
    packages:

python:
  - 3.6       # 3.6 stable/release
  - 3.6-dev   # 3.6 development branch
  - 3.7-dev   # 3.7 development branch
  - 3.8-dev   # 3.8 development branch

install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./KonekoBot.py
  - python -m compileall ./src/core
  - python -m compileall ./src/modules
  - python -m compileall ./src/services

  - python ./KonekoBot.py -t $TOKEN -d 1

cache: pip