language: python

dist: xenial

services:
  - postgresql

python:
  - 3.6-dev   # 3.6 development branch
  - 3.6       # 3.6 stable/release
  - 3.7-dev   # 3.7 development branch
  - 3.7       # 3.7 Stable/release
  - 3.8-dev   # 3.8 development branch
  - 3.8

install:
  # Install required libraries.
  - pip install -r requirements.txt

before_script:
  # Create a postgres database.
  - psql -c 'create database koneko;' -U postgres
  - PROJECT_ROOT=$(pwd)
  - cd src/utils/database
  - cp config.example.json config.json
  - cd $PROJECT_ROOT

jobs:
  allow_failures:
    - python: 3.8
  include:
    # Lint all files.
    - stage: lint
      - script: python -m compileall ./KonekoBot.py
      - script: python -m compileall ./src/core
      - script: python -m compileall ./src/cogs
      - script: python -m compileall ./src/utils
      - script: python -m compileall ./tests
    # Run tests
    - stage: test
      - script: python ./tests/pep8.py
        name: "pep8 conformance"
    # Force a boot.
    - stage: run
      - script: python KonekoBot.py -d 1

cache: pip
