language: python

dist: xenial

addons:
  apt:
    sources:
    packages:

stages:
  - lint
  - test
  - run

python:
  - 3.6       # 3.6 stable/release
  - 3.6-dev   # 3.6 development branch
  - 3.7-dev   # 3.7 development branch
  - 3.8-dev   # 3.8 development branch

install:
  - pip install -r requirements.txt

before_script:
  - ls $HOME
  - printf '' > $HOME/src/core/data/level.sqlite
  - printf '' > $HOME/src/core/data/currency.sqlite

jobs:
  include:
    - stage: lint
      sudo: false
      cache: false
      script:
        - python -m compileall ./KonekoBot.py
        - python -m compileall ./src/core
        - python -m compileall ./src/modules
        - python -m compileall ./src/services
    - stage: run
      script:
        - python KonekoBot.py -t "TOKEN" -d 1

cache: pip