name: Quality assurance

on:
    - push
    - pull_request

jobs:
    quality_assurance:
        strategy:
            matrix:
                python-version: [ 3.8 ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  pip install pycodestyle flake8 pylint

            - name: Quality assurance
              run: |
                pycodestyle . --ignore=E501
                flake8
                pylint -j 0 src tests
